name: ssn-wagtail

services:
  web:
    build: ./
    env_file: .env
    ports:
      - 127.0.0.1:8000:8000
    depends_on:
      - db
  db:
    image: public.ecr.aws/docker/library/postgres:16
    environment:
      POSTGRES_PASSWORD: development
      POSTGRES_DB: development
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
