name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install poetry
      run: pipx install poetry

    - uses: actions/setup-python@v5
      id: setup-python
      with:
        python-version: "3.12"
        cache: 'poetry'

    - name: Install dependencies
      run: |
        cd wagtail_site
        poetry install --no-root
    - name: Run tests
      run: |
        cd wagtail_site
        export DJANGO_SECRET=${{ secrets.DJANGO_SECRET }}
        poetry run python manage.py collectstatic --noinput
        poetry run pytest
        poetry run python manage.py check --deploy --settings wagtail_site.settings.production --fail-level INFO

  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v5
      with:
        cache: 'pip'
    - uses: pre-commit/action@v3.0.1
